---
- name: Upload Fuse binaries on Server
  copy:
    src: /{{ binary['folder'] }}/fuse-karaf-{{ fuse['version'] }}.fuse-{{ fuse['full_version'] }}-redhat-{{ fuse['maven_version'] }}.zip
    dest: /tmp
    force: no
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Create Fuse folder
  file:
    path: "{{ fuse_base }}/{{ esb_name }}"
    state: directory
    mode: 0755
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Create Fuse Applications folder
  file:
    path: "{{ app_home }}"
    state: directory
    mode: 0755
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Install Fuse binaries on Server
  unarchive:
    src: /tmp/fuse-karaf-{{ fuse['version'] }}.fuse-{{ fuse['full_version'] }}-redhat-{{ fuse['maven_version'] }}.zip
    dest: '{{ fuse_base }}/{{ esb_name }}'
    remote_src: true
    keep_newer: yes
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    creates: '{{ fuse_base }}/latest-{{ esb_name }}/bin'

- name: Change owner of Fuse binaries
  file:
    dest: '{{ fuse_base }}/{{ esb_name }}'
    recurse: yes
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Link current version to installed version
  file:
    src: "{{ fuse_base }}/{{ esb_name }}/fuse-karaf-{{ fuse['version'] }}.fuse-{{ fuse['full_version'] }}-redhat-{{ fuse['maven_version'] }}"
    dest: '{{ fuse_base }}/latest-{{ esb_name }}'
    state: link
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: Install systemd unit file
  template:
    src: fuse.service.j2
    dest: /etc/systemd/system/fuse7-{{ esb_name }}.service
    owner: root
    mode: 644
  notify:
    - reload systemd
    - restart fuse7-{{ esb_name }}
