---
- name: Grant RHEL and Fuse repos enabled
  shell: subscription-manager repos --enable=rhel-7-server-rpms
  register: repo_enabled
  # failed_when: "repo_enabled.rc != 0"
  ignore_errors: yes
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution != "CentOS"

- name: Create user for Fuse
  user:
    name: "{{ user['name'] }}"
    shell: "{{user['shell'] if user['shell'] is defined else '/sbin/nologin'}}"
    createhome: "{{'yes' if user['homedir'] else 'no'}}"

- name: Install Requirements and Dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - unzip
    - java-1.8.0-openjdk
    - vim
    - git

- name: Set JAVA_HOME for Fuse user
  become_user: "{{ user['name'] }}"
  lineinfile:
    dest: /home/{{ user['name'] }}/.bash_profile
    insertafter: 'EOF'
    state: present
    regexp: '^export JAVA_HOME'
    line: 'export JAVA_HOME={{ java_home }}'

- name: Source the bash_profile file
  become_user: "{{ user['name'] }}"
  shell: source /home/{{ user['name'] }}/.bash_profile

- name: Configure java security
  lineinfile:
    dest: '{{ java_home }}/lib/security/java.security'
    regexp: '^securerandom.source='
    line: 'securerandom.source=file:/dev/./urandom'
    state: present

- name: Disable firewalld service
  service: 
    name: firewalld
    enabled: no
    state: stopped
